using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Svelto.DataStructures;
using Svelto.ECS.Schema.Definition;
using Svelto.ECS.Schema.Internal;

namespace Svelto.ECS.Schema.Internal
{
    public abstract class TablesBase<TRow> : IEntityTables<TRow>, IEntityTablesBuilder<TRow>
        where TRow : class, IEntityRow
    {
        internal readonly IEntityTable<TRow>[] _tables;
        internal FasterList<ExclusiveGroupStruct> _groups;

        public string Name { get; set; }

        /// <summary>
        /// Indicates if Tables<T> is combined form of existing tables
        /// or generated by user as part of schema
        /// </summary>
        public bool IsCombined { get; }

        public int Range => _tables.Length;

        protected TablesBase(IEntityTable<TRow>[] tables, bool isCombined)
        {
            IsCombined = isCombined;

            _tables = tables;
        }

        protected LocalFasterReadOnlyList<ExclusiveGroupStruct> Build()
        {
            if (_groups != null)
                return _groups;

            _groups = _tables.Select(x => x.ExclusiveGroup).ToFasterList();
            return _groups;
        }

        public IEntityTable<TRow> this[int index] => _tables[index];
        public IEntityTable<TRow> Get(int index) => _tables[index];

        public IEntityTable<TRow> this[uint index] => _tables[index];
        public IEntityTable<TRow> Get(uint index) => _tables[index];

        public static implicit operator TablesBuilder<TRow>(TablesBase<TRow> rangedTable)
            => new TablesBuilder<TRow>(rangedTable._tables);

        IEnumerable<IEntityTable<TRow>> IEntityTablesBuilder<TRow>.Tables => _tables;

        public LocalFasterReadOnlyList<ExclusiveGroupStruct> ExclusiveGroups => Build();

        IEntityTable IEntityTables.GetTable(int index) => _tables[index];
        IEntityTable<TRow> IEntityTables<TRow>.GetTable(int index) => _tables[index];

        public override string ToString() => Name;
    }
}

namespace Svelto.ECS.Schema.Definition
{
    public sealed class CombinedTables<TRow> : TablesBase<TRow>
        where TRow : class, IEntityRow
    {
        internal CombinedTables(IEnumerable<IEntityTable<TRow>> tables) : base(tables.ToArray(), true) { }
        internal CombinedTables(FasterList<IEntityTable<TRow>> tables) : base(tables.ToArray(), true) { }
    }
}